FROM python:3.13-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && ln -s /root/.local/bin/poetry /usr/local/bin/poetry

COPY pyproject.toml poetry.lock* ./
COPY README.md .
COPY . .

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --only main --no-cache

FROM python:3.13-slim

WORKDIR /app

COPY --from=builder /usr/local /usr/local
COPY --from=builder /root/.local /root/.local
COPY --from=builder /app /app
COPY --from=builder /root/.config /root/.config

EXPOSE 8080

CMD ["poetry", "run", "python", "-m", "ml_ui.dummy_project.ui"]
