services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.dummy_project
    volumes:
    - "${ML_HOMELAB_ROOT}:${ML_HOMELAB_ROOT}:rw"
    image: "${PROJECT_NAME:-dummy_project}_${MODE:-local}_ui:latest"
    env_file:
      - path: "${ML_HOMELAB_ROOT}/.terraform_envs"
        required: false

    environment:
      - ML_HOMELAB_ROOT=${ML_HOMELAB_ROOT}
      - DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME}
      - OUTPUT_SUFFIX=${OUTPUT_SUFFIX:-dummy_project_local}
      - LOGS_DIR=${LOGS_DIR:-logs/ui}
    ports:
      - "${UI_PORT}:8080"
    networks: 
      - external_net

networks:
  external_net:
    external: true
    name: ${DOCKER_NETWORK_NAME}