services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.investing_allocation_optimizer
    volumes:
    - "${ML_HOMELAB_ROOT}:${ML_HOMELAB_ROOT}:rw"
    image: "${PROJECT_NAME:-investing_allocation_optimizer}_${MODE:-local}_ui:latest"
    env_file:
      - path: "${ML_HOMELAB_ROOT}/.terraform_envs"
        required: false

    environment:
      - ML_HOMELAB_ROOT=${ML_HOMELAB_ROOT}
      - DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME}
      - OUTPUT_SUFFIX=${OUTPUT_SUFFIX:-investing_allocation_optimizer_local}
      - LOGS_DIR=${LOGS_DIR:-logs/ui}
      - SERVING_URL=${SERVING_URL:-http://serving:8000}
    ports:
      - "${UI_PORT}:8080"
    networks: 
      - external_net

networks:
  external_net:
    external: true
    name: ${DOCKER_NETWORK_NAME}