name: Linting and testing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry --python "$(command -v python)"

      - name: Install dependencies
        run: poetry sync --no-interaction

      - name: Check Black formatting
        run: poetry run black --check .

      - name: Run Flake8
        run: poetry run flake8 .


  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry --python "$(command -v python)"

      - name: Install dependencies
        run: poetry sync --no-interaction

      - name: Run tests
        run: poetry run pytest -q
